## 1-sample test

In [2]:

import pandas as pd
from scipy import stats

In [7]:
df=pd.read_csv('tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [5]:
our_column=df['tip']
our_column=our_column.sample(n=30, replace=False)

meu=3   #we assume that avg tip is $3 and want to test it

# H0: avg tip = $3
# H1: avg tip <> $3

t_stat, p_value= stats.ttest_1samp(our_column, meu)
print('p_value: ',p_value)

p_value:  0.45753034973598855

In [6]:
alpha=0.05
if p_value < alpha:
    print('reject H0')

else:
    print("Do not reject H0")

Do not reject H0

## 2-Sample/independent t-test

In [9]:
male_tips= df[df['sex']=='Male']['tip']
female_tips= df[df['sex']=='Female']['tip']

male_tips= male_tips.sample(n=30, replace=False)
female_tips= female_tips.sample(n=30, replace=False)

t_stat, p_value= stats.ttest_ind(male_tips, female_tips)
print('p_value: ',p_value)

p_value:  0.2077973775870081

In [10]:
if p_value < alpha:
    print('reject H0')

else:
    print("Do not reject H0")

Do not reject H0

## Paired t-test

In [13]:
df=pd.read_csv('hypothermia.csv')
df= df[['t.1', 't.2']].dropna()
df.head()

    t.1   t.2
0  34.0  35.1
1  29.0  33.0
2  31.0  36.8
3  32.0  34.0
4  32.2  36.6

In [14]:
sample_df= df.sample(n=30, replace=False)
t_stat, p_value= stats.ttest_rel(sample_df['t.1'], sample_df['t.2'] )
print('p_value: ',p_value)

p_value:  1.3434925116224667e-11

In [15]:
if p_value < alpha:
    print('reject H0')
else:
    print("Do not reject H0")

# H0: Treatment is not effective
# H1: Treatment is effective

reject H0

## ANOVA

In [16]:
from scipy.stats import f_oneway

In [19]:
df =pd.read_csv('tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [21]:
# size is a keyword so we might have problems later

df.rename(columns={'size': 'customer_count'}, inplace=True)
df['tip_to_total']= df['tip'] / df['total_bill']

s1 = df.tip_to_total[df.customer_count==1]
s2 = df.tip_to_total[df.customer_count==2]
s3 = df.tip_to_total[df.customer_count==3]
s4 = df.tip_to_total[df.customer_count==4]
s5 = df.tip_to_total[df.customer_count==5]
s6 = df.tip_to_total[df.customer_count==6]

## Chi-square test

In [22]:
# test if two categorical variables are related or not
from scipy.stats import chi2_contingency

In [26]:
df = pd.read_csv("titanic.csv")
df = df[['pclass', 'survived']].dropna()
df

     pclass  survived
0         3         0
1         1         1
2         3         1
3         1         1
4         3         0
..      ...       ...
886       2         0
887       1         1
888       3         0
889       1         1
890       3         0

[891 rows x 2 columns]

In [27]:
contingency_table = pd.crosstab(df["pclass"], df["survived"])
print(contingency_table)

survived    0    1
pclass
1          80  136
2          97   87
3         372  119

In [28]:
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
print('p_value: ',p_value)

p_value:  4.549251711298793e-23

In [29]:
if p_value < alpha:
    print('reject H0')
else:
    print("Do not reject H0")

reject H0