In [1]:
import pandas as pd
import seaborn as sns

In [10]:
#Load tips dataset

df=sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
# 1.Boolean Filtering

df[df['total_bill']>20].head()

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [15]:
# 2.Multiple Conditions

df[(df['total_bill'] > 20) & (df['tip']<3)].head()

    total_bill   tip     sex smoker  day    time  size
21       20.29  2.75  Female     No  Sat  Dinner     2
33       20.69  2.45  Female     No  Sat  Dinner     4
48       28.55  2.05    Male     No  Sun  Dinner     3
57       26.41  1.50  Female     No  Sat  Dinner     2
68       20.23  2.01    Male     No  Sat  Dinner     2

In [17]:
# 3. .loc[] Filtering + Select Columns

df.loc[df['size'] ==2,['total_bill','tip','sex','size']].head()

   total_bill   tip     sex  size
0       16.99  1.01  Female     2
3       23.68  3.31    Male     2
6        8.77  2.00    Male     2
8       15.04  1.96    Male     2
9       14.78  3.23    Male     2

In [19]:
# 4.query

df.query("total_bill > 20 and tip < 3").head()

    total_bill   tip     sex smoker  day    time  size
21       20.29  2.75  Female     No  Sat  Dinner     2
33       20.69  2.45  Female     No  Sat  Dinner     4
48       28.55  2.05    Male     No  Sun  Dinner     3
57       26.41  1.50  Female     No  Sat  Dinner     2
68       20.23  2.01    Male     No  Sat  Dinner     2

In [21]:
# 5. isin()

df[df['day'].isin(['Fri'])].head()

    total_bill   tip     sex smoker  day    time  size
90       28.97  3.00    Male    Yes  Fri  Dinner     2
91       22.49  3.50    Male     No  Fri  Dinner     2
92        5.75  1.00  Female    Yes  Fri  Dinner     2
93       16.32  4.30  Female    Yes  Fri  Dinner     2
94       22.75  3.25  Female     No  Fri  Dinner     2

In [22]:
# 6. between()

df[df['total_bill'].between(15,25)].head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2

In [23]:
# 7. String Filter

df[df['sex'].astype(str).str.contains("Male")].head()

   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3
3       23.68  3.31  Male     No  Sun  Dinner     2
5       25.29  4.71  Male     No  Sun  Dinner     4
6        8.77  2.00  Male     No  Sun  Dinner     2

In [26]:
# 8. Top Values

df.nlargest(10,'tip')

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
183       23.17   6.50    Male    Yes   Sun  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
47        32.40   6.00    Male     No   Sun  Dinner     4
239       29.03   5.92    Male     No   Sat  Dinner     3
88        24.71   5.85    Male     No  Thur   Lunch     2